// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visible countdown while the core turn waits to retry after a usage-limit reset.
 */
export type UsageLimitWaitChangedNotification = { threadId: string,
/**
 * Unix timestamp in milliseconds for the next retry, or `None` when the wait ended.
 */
retryAtMs: bigint | null, };
